title: Cisse Amina 
logo: /assets/img/Profile.jpg
description: Data Analyst | Cooking & Baking Enthusiast
#show_dowloads: true
theme: jekyll-theme-minimal
sass:
  style: compressed

include:
  - index.md
  - projects/
