title: Cisse Amina 
#logo: /Design sans titre.jpg
#description:A resilient and intuitive problem solver, skilled at navigating diverse perspectives and turning complex data into clear insights. Agile and precise, I balance flexibility with structure to uncover clarity in complexity.
#show_dowloads: true
theme: jekyll-theme-minimal
email: cisse.aminabintou@gmail.com
phone: 06.51.63.96.76

 
