title: Cisse Amina 
#logo: /Design sans titre.jpg
description: Data Analyst | Cooking & Baking Enthusiast
#show_dowloads: true
theme: jekyll-theme-minimal
email: cisse.aminabintou@gmail.com
phone: 06 51 63 96 76

 
