title: Cisse Amina 
logo: assets/Profile.jpg
description: Data Analyst | Cooking & Baking Enthusiast
#show_dowloads: true
theme: jekyll-theme-minimal

nav:
  - README: /README/
  - Projects: /projects/


 
